### ISSUE TITLE
Impossible to raise both flippers simultaneously in portrait mode

### ISSUE THREAD

**Issue by tomrow** [headshot2017/3dpinball-nds#2]
With the current control mapping for Portrait mode, it is impossible to raise both flippers simultaneously, as they are mapped to opposite ends of the + Pad, and have no alternative inputs available. Please consider adding another input to activate both flippers, or adding a flipped portrait mode that uses the ABXY buttons instead of the + Pad for flipper control

**Comment by headshot2017** [comment]
![image](https://github.com/headshot2017/3dpinball-nds/assets/36455681/515ac556-8df6-413d-a409-db6c5895062e)
